#!/bin/bash
if mountpoint -q /media/usb1
then
   if mountpoint -q /media/usb2
   then
      if mountpoint -q /media/usb3
      then
         if mountpoint -1 /media/usb4
         then
             echo "No mountpoints available!"
             #You can add more if you need
         else
             /usr/bin/pmount --umask 000 --noatime -w --sync $1 usb4
             sudo -u pi /home/pi/oprint/bin/octoprint client get '/api/plugin/usbfileman'
         fi
      else
         /usr/bin/pmount --umask 000 --noatime -w --sync $1 usb3
         sudo -u pi /home/pi/oprint/bin/octoprint client get '/api/plugin/usbfileman'
      fi
   else
      /usr/bin/pmount --umask 000 --noatime -w --sync $1 usb2
      sudo -u pi /home/pi/oprint/bin/octoprint client get '/api/plugin/usbfileman'
   fi
else
   /usr/bin/pmount --umask 000 --noatime -w --sync $1 usb1
   sudo -u pi /home/pi/oprint/bin/octoprint client get '/api/plugin/usbfileman'
fi
